### ISSUE TITLE
无法查看并输入验证码，建议添加支持显示Google流量异常验证的代码

### ISSUE THREAD

**Issue by cjh0613** [upupming/Mirror#3]
无法查看并输入验证码，建议添加支持显示Google流量异常验证的代码

**Comment by upupming** [comment]
无法输入验证码的话，重新部署一遍就好了

**Comment by cjh0613** [comment]
> 无法输入验证码的话，重新部署一遍就好了

重新部署后第二次google搜索时，又出现流量异常验证，但无法显示。
![image](https://user-images.githubusercontent.com/25498029/79627410-8371a100-816a-11ea-9c56-07dbba248fe2.png)

**Comment by cjh0613** [comment]
now.sh
Mirror v0.0.2

**Comment by upupming** [comment]
这个暂时没有很好的办法解决。

**Comment by cjh0613** [comment]
> 这个暂时没有很好的办法解决。

另外，还有一个比较好解决的问题，我使用`npm run deploy`无法自动推至now.sh，我是取消清理文件，手动进入各文件夹上传的。

![image](https://user-images.githubusercontent.com/25498029/79627511-75705000-816b-11ea-8cf1-3cef650caebd.png)

**Comment by upupming** [comment]
为什么会无法自动推送？

**Comment by upupming** [comment]
@cjh0613 如果找到原因的话，可以麻烦 PR 一下么，我这边暂时没有配置相关的环境，无法测试了。

**Comment by cjh0613** [comment]
@upupming 我觉得可能是now.sh cli 工具升级后推送时添加了询问。您当初推送时是这些提示吗？
![image](https://user-images.githubusercontent.com/25498029/79627684-ecf2af00-816c-11ea-90d3-da6adc33513d.png)

**Comment by upupming** [comment]
我之前没有这些 `[Y/n]` 选项，你可以看 README 最后部分的 log。如果是这样的话，可以尝试先降级一下 now.sh:

```bash
npm -g i now@12.0.0
```

**Comment by upupming** [comment]
已经更新了 README:

![image](https://user-images.githubusercontent.com/24741764/79627890-bfa70080-816e-11ea-86c1-52169c60e5ed.png)
